kind: pipeline
type: docker
name: default

steps:
- name: test
  image: ruby
  commands:
  - bundle install
  - bundle exec scraper.rb


- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 1625256489:AAG-x-4cABWDDqCDIfDA-wprs_rHuv_6XFc
    to: 1571728109
